# Updated 2024-04-18 16:01:23
apiVersion: v1
kind: ConfigMap
metadata:
  name: azd-env-configmap
data:
  API_ALLOW_ORIGINS: ""
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=6fa478c2-3ea8-451e-8350-acafdaf6264a;IngestionEndpoint=https://francecentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://francecentral.livediagnostics.monitor.azure.com/;ApplicationId=cc2958e9-c1f3-4fc8-910f-49d81979c208"
  AZURE_AKS_CLUSTER_NAME: "aks-yvh3rjtnvwvvm"
  AZURE_CLIENT_ID: "19ccc9b6-37b0-47ce-b99e-efddf02bef26"
  AZURE_CONTAINER_REGISTRY_ENDPOINT: "cryvh3rjtnvwvvm.azurecr.io"
  AZURE_CONTAINER_REGISTRY_NAME: "cryvh3rjtnvwvvm"
  AZURE_ENV_NAME: "java-chat-12-aks-test"
  AZURE_FORMRECOGNIZER_RESOURCE_GROUP: "rg-java-chat-12-aks-test"
  AZURE_FORMRECOGNIZER_SERVICE: "cog-fr-yvh3rjtnvwvvm"
  AZURE_KEY_VAULT_ENDPOINT: "https://kv-yvh3rjtnvwvvm.vault.azure.net/"
  AZURE_LOCATION: "francecentral"
  AZURE_OPENAI_CHATGPT_DEPLOYMENT: "chat"
  AZURE_OPENAI_CHATGPT_MODEL: "gpt-35-turbo"
  AZURE_OPENAI_EMB_DEPLOYMENT: "embedding"
  AZURE_OPENAI_EMB_MODEL_NAME: "text-embedding-ada-002"
  AZURE_OPENAI_RESOURCE_GROUP: "rg-java-chat-12-aks-test"
  AZURE_OPENAI_SERVICE: "cog-yvh3rjtnvwvvm"
  AZURE_RESOURCE_GROUP: "rg-java-chat-12-aks-test"
  AZURE_SEARCH_INDEX: "gptkbindex"
  AZURE_SEARCH_SERVICE: "gptkb-yvh3rjtnvwvvm"
  AZURE_SEARCH_SERVICE_RESOURCE_GROUP: "rg-java-chat-12-aks-test"
  AZURE_SERVICEBUS_NAMESPACE: "sb-yvh3rjtnvwvvm"
  AZURE_SERVICEBUS_SKU_NAME: "Standard"
  AZURE_STORAGE_ACCOUNT: "styvh3rjtnvwvvm"
  AZURE_STORAGE_CONTAINER: "content"
  AZURE_STORAGE_RESOURCE_GROUP: "rg-java-chat-12-aks-test"
  AZURE_SUBSCRIPTION_ID: "8b82fc4d-aabe-4658-88f2-5674bf49eec0"
  AZURE_TENANT_ID: "fa3408a7-4997-49b5-bda2-62886815fa49"
  OPENAI_API_KEY: ""
  OPENAI_HOST: "azure"
  OPENAI_ORGANIZATION: ""
  REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=6fa478c2-3ea8-451e-8350-acafdaf6264a;IngestionEndpoint=https://francecentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://francecentral.livediagnostics.monitor.azure.com/;ApplicationId=cc2958e9-c1f3-4fc8-910f-49d81979c208"
  SERVICE_API_ENDPOINT_URL: "http://68.220.199.26"
  SERVICE_API_IMAGE_NAME: "crnq6gqbtyxqno2.azurecr.io/azure-search-openai-demo/api-java-chat-12-aks-test:azd-deploy-1710941647"
  SERVICE_FRONTEND_ENDPOINT_URL: "http://10.0.118.173:80"
  SERVICE_FRONTEND_IMAGE_NAME: "crnq6gqbtyxqno2.azurecr.io/azure-search-openai-demo/frontend-java-chat-12-aks-test:azd-deploy-1710941650"
  SERVICE_INDEXER_ENDPOINT_URL: "http://10.0.165.214:80"
  SERVICE_INDEXER_IMAGE_NAME: "crnq6gqbtyxqno2.azurecr.io/azure-search-openai-demo/indexer-java-chat-12-aks-test:azd-deploy-1710941756"

