name: Reusable Azure Container Apps deploy
on:
    workflow_call:
      inputs:
        env-name:
          required: true
          type: string
        image-name:
          required: true
          type: string
        container-app-name:
          required: true
          type: string
        container-app-env-name:
          required: true
          type: string
      

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{inputs.env-name}}
        steps:
        - name: Log in to Azure with service principal
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v1
          with:
              acrName: ${{vars.ACR_NAME}}
              containerAppName: ${{inputs.container-app-name}}
              containerAppEnvironment: ${{inputs.container-app-env-name}}
              resourceGroup: ${{vars.RESOURCE_GROUP}}
              imageToDeploy: ${{vars.ACR_NAME}}.azurecr.io/${{inputs.image-name}}:${{github.sha}}