name: Reusable ACR Build and Push workflow
on:
    workflow_call:
      inputs:
        env-name:
          required: true
          type: string
        image-name:
          required: true
          type: string
        app-folder-path:
          required: true
          type: string
      

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ${{inputs.env-name}}
        steps:
        - name: Log in to Azure with service principal
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Log in Azure Container Registry
          uses: azure/docker-login@v2
          with:
            login-server: ${{vars.ACR_NAME}}.azurecr.io
            username: ${{ secrets.SPI_CLIENT_ID   }}
            password: ${{ secrets.SPI_CLIENT_SECRET }}
        - uses: actions/checkout@v2
        - name: Build and Push to ACR
          run: |
            echo "Building image [${{ inputs.image-name }}] and environment [${{ inputs.env-name }}]"
            cd ${{ inputs.app-folder-path }}
            docker build . -t ${{vars.ACR_NAME}}.azurecr.io/${{inputs.image-name}}:${{github.sha}}
            docker push ${{vars.ACR_NAME}}.azurecr.io/${{inputs.image-name}}:${{github.sha}}
            echo "image successfully pushed: ${{vars.ACR_NAME}}.azurecr.io/${{inputs.image-name}}:${{github.sha}}"